#
# Kibana Dockerfile
#
# https://github.com/ibbd/dockerfile-elk/kibana
#
#

# Pull base image.
FROM kibana:4.5

MAINTAINER Alex Cai "cyy0523xc@gmail.com"


# 解决时区问题
ENV TZ "Asia/Shanghai"

# 终端设置
ENV TERM xterm


EXPOSE 5601
