#!/bin/bash

usage() {
    echo "$0 run   创建并运行容器"
    echo "$0 exec  进入容器"
    echo "$0 start 启动容器"
    echo "$0 stop  停止容器"
}

if [ $# = 0 ]; then
    usage
    exit 1
fi

# 容器名称
name=ibbd-kibana

# 对外端口
port=5601

# es url
es_url="http://10.132.31.214:9200"

case $1 in
    run)
        docker run --name "$name" \
            -e ELASTICSEARCH_URL="$es_url" \
            -p $port:$port \
            -v /var/www:/var/www \
            -d kibana
        ;;
    exec)
        sudo docker exec --interactive "$name" /bin/sh
        ;;
    start)
        sudo docker start "$name"
        ;;
    stop)
        sudo docker stop "$name"
        ;;
    *)
        echo 'error params'
        echo
        usage
        ;;
esac
