#
# ElasticSearch Dockerfile with IK plugin for chinese
#
# https://github.com/ibbd/dockerfile-elk/elasticsearch
#

FROM openjdk:8-slim

MAINTAINER Alex Cai "cyy0523xc@gmail.com"

ENV ES_VERSION 5.4.3
ENV ES_FILE elasticsearch-$ES_VERSION.deb
ENV PATH /usr/share/elasticsearch/bin:$PATH

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
    && wget https://artifacts.elastic.co/downloads/elasticsearch/$ES_FILE \
    && sha1sum $ES_FILE \
    && dpkg -i $ES_FILE \
    && rm $ES_FILE \
    && apt-get remove -y \
        wget \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/* \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'vm.max_map_count=262144' | tee -a /etc/sysctl.conf

# 解决时区问题
ENV TZ "Asia/Shanghai"

# 终端设置
ENV TERM xterm

EXPOSE 9300
EXPOSE 9200
