#
# ElasticSearch Dockerfile with IK plugin for chinese
#
# https://github.com/ibbd/dockerfile-elk/elasticsearch
#

FROM openjdk:8-slim

MAINTAINER Alex Cai "cyy0523xc@gmail.com"

ENV ES_VERSION 5.4.3
ENV ES_FILE elasticsearch-$ES_VERSION.deb
ENV PATH /usr/share/elasticsearch/bin:$PATH

# install es
# 注意：卸载不需要的x-pack
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        wget \
    && wget https://artifacts.elastic.co/downloads/elasticsearch/$ES_FILE \
    && sha1sum $ES_FILE \
    && dpkg -i $ES_FILE \
    && rm $ES_FILE \
    && apt-get remove -y \
        wget \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -r /var/lib/apt/lists/* \
    && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && echo 'vm.max_map_count=262144' | tee -a /etc/sysctl.conf

# grab gosu for easy step-down from root
ENV GOSU_VERSION 1.10
RUN set -x \
	&& wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
	&& wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
	&& export GNUPGHOME="$(mktemp -d)" \
	&& gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 \
	&& gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu \
	&& rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc \
	&& chmod +x /usr/local/bin/gosu \
	&& gosu nobody true

# 工作目录
WORKDIR /usr/share/elasticsearch

# 处理运行用户
RUN chown -R elasticsearch:elasticsearch /usr/share/elasticsearch 

# 解决时区问题
ENV TZ "Asia/Shanghai"

# 终端设置
ENV TERM xterm

# 配置文件
COPY config ./config

VOLUME /usr/share/elasticsearch/data

COPY docker-entrypoint.sh /

EXPOSE 9200 9300
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["elasticsearch"]
