#
# ElasticSearch Web UI
#
# https://github.com/appbaseio/dejavu
#
#

# Pull base image.
FROM appbaseio/dejavu

MAINTAINER Alex Cai "cyy0523xc@gmail.com"

# 解决时区问题
ENV TZ "Asia/Shanghai"

# 终端设置
ENV TERM xterm

